# Pull Requests to Main
name: Pull Requests to Main

on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release_branch: main
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CALVER_EX_CONTENTS_PAT }}

      # - name: Deploy
      #   env:
      #     VERSION: ${{ steps.calver.outputs.release }}
      #   run: ./deploy ${VERSION}