name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: echo "Current environment '${{ vars.ENVIRONMENT_TYPE }}'"
  
  deploy-development:
    name: Deploy Development Environment
    environment: Development
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Environment
        run: echo "Current environment '${{ vars.ENVIRONMENT_TYPE }}'"

  deploy-staging:
    name: Deploy Staging Environment
    environment: Staging
    needs:
      - build
      - deploy-development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Environment
        run: echo "Current environment '${{ vars.ENVIRONMENT_TYPE }}'"

      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y.%m.%d"
          release_branch: main
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CALVER_EX_CONTENTS_PAT }}

  deploy-production:
    name: Deploy Production Environment
    environment: Production
    needs:
      - build
      - deploy-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Environment
        run: echo "Current environment '${{ vars.ENVIRONMENT_TYPE }}'"

  